Api/laggner
team-abalone/abalone-api pull request #2
Opened 2021-04-29 10:51 UTC by alexlaggner

Grundlegende Servereigenschaften implementiert

2021-04-29 16:43 UTC, luko0610 requested changes
Zusätzliche zu Kommentaren: prettier installieren und vor commit ausführen.

2021-04-29 16:43 UTC, luko0610 commented on Controls/controls.js
> +       socket.name = `${socket.remoteAddress} : ${socket.remotePort}`;  //later identifies corresponding socket
Das wird nicht funktionieren, bzw. spätestens wenn zwei Spieler aus demselben Netzwerk kommen.

2021-04-29 16:43 UTC, luko0610 commented on Controls/controls.js
> +        let roomKeyNew = roomKey.split('')[0] + roomKey.split('')[1] + roomKey.split('')[2] + roomKey.split('')[3] + roomKey.split('')[4];
1. 5 mal splitten, anstatt einmal zu splitten und dann auf das result zuzugreifen.
2. Generell das Splitten vermeiden und dafür dann die JSON Struktur mit commandCode / props verwenden:

2021-04-29 16:43 UTC, luko0610 commented on Controls/controls.js
> +        for (let i = 0; i < rooms.length; i++) {
Javascript find method.
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2021-04-29 16:43 UTC, luko0610 commented on src/index.js
> +        let type = (d.toString()).split(" ")[0];
JSON Struktur mit commandCode / props einführen.
Generell JSON Datenstrukturen retournieren.

2021-04-29 16:43 UTC, luko0610 commented on src/index.js
> +        // further types could occur depending on final game (cheat function, etc)
Multiline comments mit /* */ machen.

2021-04-29 16:43 UTC, luko0610 commented on .vs/ProjectSettings.json
> +}
nicht committen / in .gitignore einfügen.

2021-05-01 13:52 UTC, alexlaggner commented on src/Controls/RoomControls.js
> +    let roomToJoin = this.rooms.find((r) => r.roomKey == roomKey);
'===' statt '==' wäre möglicherweise besser

2021-05-01 13:53 UTC, alexlaggner commented on src/Controls/RoomControls.js
> +    let roomToJoin = this.rooms.find((r) => r.roomKey == roomKey);
Line 38: Besser wäre '===' statt '=='

2021-05-01 13:54 UTC, alexlaggner commented on src/Controls/RoomControls.js
> +    let room = this.rooms.find((r) => r.roomKey == roomKey);
Line 84: auch wieder '==='

2021-05-01 14:30 UTC, luko0610 approved these changes

2021-05-01 14:30 UTC, merged